name: MLOPS CI CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-test-train:
        runs-on: ubuntu-latest

        steps:
            # step 1: Checkout source code
            - name: Checkout repository 
              uses: actions/checkout@v4

            
            # step 2: Setup Python Environment
            - name: Setup Python
              uses: actions/setup-python@v5

              with:
                pyhton-versions: "3.10"
  
            
            # step 3: Install dependencies
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            
            # step 4: run unit test
            - name: Run unit tests
              run: pytest -v

            
            # step 5: Train the model 
            - name: Train model
              run: python src/train.py

            # step 6: Evaluate the model
            - name: Evaluate model
              run: python src/evaluate.py

            # step 7: upload the train model as artifact
            - name: Upload model artifact
              uses: actions/upload-artifact@v4

              with:
                name: trained-model
                path: models/model.pkl


    
    deploy:
        needs: build-test-train
        runs-on: ubuntu-latest


        steps:
            # step 8: Download the trained model
            - name: Download model artifact
              uses: actions/download-artifact@v4

              with:
                name: trained-model
                path: models

            
            # step 9: Deployment simulations
            - name: Deployment simulations
              run: 
                echo "Model deployed successfully"
                ls -l models
